export interface SyncTableConfig {
	doctype: string;
	label: string;
	pullMethod?: string;
	pushMethod?: string;
	fields: string[];
	filters?: Record<string, unknown>;
	orderBy: string;
	direction: "pull" | "push" | "both";
	idbStore: string;
	primaryKey?: string;
	localIdField: string;
	incremental: boolean;
	batchSize: number;
	pullOrder: number;
	dependsOn?: string[];
	parentDoctype?: string;
	isCompanyBased?: boolean;
	regetAll?: boolean;
}

export const SYNC_TABLES: SyncTableConfig[] = [
	{
		doctype: "Company",
		label: "Companies",
		fields: ["name", "company_name", "abbr", "default_currency", "country"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "companies",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 100,
		pullOrder: 1,
		isCompanyBased: false,
	},
	{
		doctype: "Country",
		label: "Countries",
		fields: ["name", "code"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "countries",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 2,
	},
	{
		doctype: "Currency",
		label: "Currencies",
		fields: ["name", "currency_name", "symbol", "enabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "currencies",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 2,
	},
	{
		doctype: "UOM",
		label: "Units of Measure",
		fields: ["name", "uom_name", "enabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "uom",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 2,
	},
	{
		doctype: "Brand",
		label: "Brands",
		fields: ["name", "brand"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "brands",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 3,
	},
	{
		doctype: "Industry Type",
		label: "Industries",
		fields: ["name", "industry"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "industries",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 3,
	},
	{
		doctype: "Mode of Payment",
		label: "Modes of Payment",
		fields: ["name", "mode_of_payment", "type", "enabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "modes_of_payment",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 3,
	},
	{
		doctype: "Cost Center",
		label: "Cost Centers",
		fields: ["name", "cost_center_name", "parent_cost_center", "is_group", "company"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "cost_centers",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 4,
		isCompanyBased: true,
	},
	{
		doctype: "Warehouse",
		label: "Warehouses",
		fields: ["name", "warehouse_name", "parent_warehouse", "is_group", "company", "disabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "warehouses",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 4,
		isCompanyBased: true,
	},
	{
		doctype: "Account",
		label: "Accounts",
		fields: [
			"name",
			"account_name",
			"account_type",
			"parent_account",
			"root_type",
			"is_group",
			"company",
			"disabled",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "accounts",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 4,
		isCompanyBased: true,
	},
	{
		doctype: "Price List",
		label: "Price Lists",
		fields: ["name", "price_list_name", "buying", "selling", "currency", "enabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "price_lists",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 4,
		isCompanyBased: true,
	},
	{
		doctype: "Mode of Payment Account",
		label: "Mode of Payment Accounts",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "company", "default_account"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "mode_of_payment_accounts",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 4,
		isCompanyBased: true,
		parentDoctype: "Mode of Payment",
	},
	{
		doctype: "POS Profile",
		label: "POS Profiles",
		fields: [
			"name",
			"company",
			"warehouse",
			"cost_center",
			"currency",
			"selling_price_list",
			"write_off_account",
			"write_off_cost_center",
			"customer",
			"income_account",
			"expense_account",
			"taxes_and_charges",
			"tax_category",
			"apply_discount_on",
			"disabled",
			"allow_rate_change",
			"hide_images",
			"hide_unavailable_items",
			"block_sale_beyond_available_qty",
			"display_items_in_stock",
			"cash_mode_of_payment",
			"apply_customer_discount",
			"allow_print_draft_invoices",
			"use_offline_mode",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pos_profiles",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 100,
		pullOrder: 5,
		isCompanyBased: true,
		dependsOn: ["companies", "warehouses", "accounts"],
	},
	{
		doctype: "Item Group",
		label: "Item Groups",
		fields: ["name", "parent_item_group", "is_group", "image"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_groups",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 500,
		pullOrder: 5,
	},
	{
		doctype: "Item",
		label: "Items",
		fields: [
			"item_code",
			"item_name",
			"local_item_name",
			"item_group",
			"brand",
			"description",
			"stock_uom",
			"image",
			"has_serial_no",
			"has_batch_no",
			"has_variants",
			"variant_of",
			"is_stock_item",
			"disabled",
			"standard_rate",
		],
		filters: { disabled: 0 },
		orderBy: "modified",
		direction: "pull",
		idbStore: "items",
		primaryKey: "item_code",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 10,
		dependsOn: ["item_groups", "brands"],
	},
	{
		doctype: "Item Barcode",
		label: "Item Barcodes",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "barcode", "barcode_type"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_barcodes",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 11,
		parentDoctype: "Item",
		dependsOn: ["items"],
	},
	{
		doctype: "UOM Conversion Detail",
		label: "UOM Conversions",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "uom", "conversion_factor"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "uom_conversion_details",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 11,
		parentDoctype: "Item",
		dependsOn: ["items", "uom"],
	},
	{
		doctype: "Item Price",
		label: "Item Prices",
		pullMethod: "xpos.api.sync.get_item_prices",
		fields: [
			"name",
			"item_code",
			"item_name",
			"price_list",
			"buying",
			"selling",
			"currency",
			"price_list_rate",
			"uom",
			"valid_from",
			"valid_upto",
			"modified",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_prices",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 12,
		dependsOn: ["items", "price_lists"],
	},
	{
		doctype: "Item Tax",
		label: "Item Taxes",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "item_tax_template", "tax_category", "valid_from"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_taxes",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 12,
		parentDoctype: "Item",
		dependsOn: ["items"],
	},
	{
		doctype: "Item Supplier",
		label: "Item Vendors",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "supplier"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_vendors",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 12,
		isCompanyBased: true,
		parentDoctype: "Item",
		dependsOn: ["items", "suppliers"],
	},
	{
		doctype: "Item Reorder",
		label: "Item Reorder Levels",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "warehouse", "warehouse_reorder_level", "warehouse_reorder_qty"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_reorder_levels",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 12,
		isCompanyBased: true,
		parentDoctype: "Item",
		dependsOn: ["items", "warehouses"],
	},
	{
		doctype: "Item Tax Template",
		label: "Item Tax Templates",
		fields: ["name", "title", "company", "disabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_tax_templates",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 13,
		isCompanyBased: true,
	},
	{
		doctype: "Item Tax Template Detail",
		label: "Item Tax Template Details",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "tax_type", "tax_rate"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "item_tax_template_details",
		localIdField: "xpos_local_id",
		incremental: false,
		regetAll: true,
		batchSize: 500,
		pullOrder: 14,
		parentDoctype: "Item Tax Template",
		dependsOn: ["item_tax_templates"],
	},
	{
		doctype: "Sales Taxes and Charges Template",
		label: "Sales Tax Templates",
		fields: ["name", "title", "company", "tax_category", "disabled"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "sales_taxes_templates",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 13,
		isCompanyBased: true,
	},
	{
		doctype: "Sales Taxes and Charges",
		label: "Sales Tax Charges",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: [
			"name",
			"parent",
			"charge_type",
			"account_head",
			"description",
			"rate",
			"tax_amount",
			"included_in_print_rate",
			"idx",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "sales_taxes_charges",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 14,
		parentDoctype: "Sales Taxes and Charges Template",
		dependsOn: ["sales_taxes_templates"],
	},
	{
		doctype: "Pricing Rule",
		label: "Pricing Rules",
		fields: [
			"name",
			"title",
			"apply_on",
			"price_or_product_discount",
			"rate_or_discount",
			"selling",
			"buying",
			"applicable_for",
			"company",
			"customer",
			"customer_group",
			"territory",
			"sales_partner",
			"campaign",
			"for_price_list",
			"warehouse",
			"min_qty",
			"max_qty",
			"min_amt",
			"max_amt",
			"valid_from",
			"valid_upto",
			"discount_percentage",
			"discount_amount",
			"rate",
			"margin_type",
			"margin_rate_or_amount",
			"priority",
			"disable",
			"is_cumulative",
			"mixed_conditions",
			"coupon_code_based",
			"same_item",
			"free_item",
			"free_qty",
			"free_item_rate",
			"free_item_uom",
			"round_free_qty",
			"is_recursive",
			"recurse_for",
			"apply_recursion_over",
		],
		filters: { disable: 0, selling: 1 },
		orderBy: "modified",
		direction: "pull",
		idbStore: "pricing_rules",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 15,
		isCompanyBased: true,
	},
	{
		doctype: "Pricing Rule Item Code",
		label: "Pricing Rule Items",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "item_code"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pricing_rule_item_codes",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 16,
		parentDoctype: "Pricing Rule",
		dependsOn: ["pricing_rules"],
	},
	{
		doctype: "Pricing Rule Item Group",
		label: "Pricing Rule Groups",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "item_group"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pricing_rule_item_groups",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 16,
		parentDoctype: "Pricing Rule",
		dependsOn: ["pricing_rules"],
	},
	{
		doctype: "Pricing Rule Brand",
		label: "Pricing Rule Brands",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "brand"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pricing_rule_brands",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 16,
		parentDoctype: "Pricing Rule",
		dependsOn: ["pricing_rules"],
	},
	{
		doctype: "Customer",
		label: "Customers",
		fields: [
			"name",
			"customer_name",
			"customer_group",
			"customer_type",
			"territory",
			"tax_category",
			"mobile_no",
			"email_id",
			"default_currency",
			"loyalty_program",
			"disabled",
		],
		filters: { disabled: 0 },
		orderBy: "modified",
		direction: "both",
		idbStore: "customers",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 20,
	},
	{
		doctype: "Supplier",
		label: "Suppliers",
		fields: [
			"name",
			"supplier_name",
			"supplier_group",
			"supplier_type",
			"default_currency",
			"mobile_no",
			"email_id",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "suppliers",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 25,
	},
	{
		doctype: "Bin",
		label: "Stock Bins",
		fields: [
			"name",
			"item_code",
			"warehouse",
			"actual_qty",
			"projected_qty",
			"reserved_qty",
			"ordered_qty",
		],
		orderBy: "modified",
		direction: "pull",
		idbStore: "bins",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 30,
		dependsOn: ["items", "warehouses"],
	},
	{
		doctype: "POS User",
		label: "POS Users",
		pullMethod: "xpos.api.auth.get_pos_users",
		fields: ["*"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pos_users",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 100,
		pullOrder: 35,
	},
	{
		doctype: "POS Payment Method",
		label: "POS Payment Methods",
		pullMethod: "xpos.api.sync.get_child_table_data",
		fields: ["name", "parent", "mode_of_payment", "default"],
		orderBy: "modified",
		direction: "pull",
		idbStore: "pos_payment_methods",
		localIdField: "xpos_local_id",
		incremental: true,
		batchSize: 500,
		pullOrder: 6,
		parentDoctype: "POS Profile",
		dependsOn: ["pos_profiles", "modes_of_payment"],
	},
	{
		doctype: "POS Opening Shift",
		label: "POS Opening Shifts",
		pushMethod: "xpos.api.shifts.create_opening_shift",
		fields: ["*"],
		orderBy: "creation",
		direction: "push",
		idbStore: "pos_opening_shifts",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 50,
		pullOrder: 98,
	},
	{
		doctype: "POS Closing Shift",
		label: "POS Closing Shifts",
		pushMethod: "xpos.api.shifts.create_closing_shift",
		fields: ["*"],
		orderBy: "creation",
		direction: "push",
		idbStore: "pos_closing_entries",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 50,
		pullOrder: 99,
		dependsOn: ["pos_opening_shifts"],
	},
	{
		doctype: "POS Invoice",
		label: "POS Invoices",
		pushMethod: "xpos.api.invoices.create_invoice",
		fields: ["*"],
		orderBy: "creation",
		direction: "push",
		idbStore: "pending_invoices",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 50,
		pullOrder: 100,
		dependsOn: ["pos_opening_shifts"],
	},
	{
		doctype: "Purchase Order",
		label: "Purchase Orders",
		pushMethod: "xpos.x_pos.api.purchase_orders.create_purchase_order",
		fields: ["*"],
		orderBy: "creation",
		direction: "push",
		idbStore: "pending_purchases",
		localIdField: "xpos_local_id",
		incremental: false,
		batchSize: 50,
		pullOrder: 110,
		dependsOn: ["suppliers", "items"],
	},
];

const PRIMARY_KEY_BY_STORE: Record<string, string> = Object.fromEntries(
	SYNC_TABLES.filter((t) => t.primaryKey).map((t) => [t.idbStore, t.primaryKey as string]),
);

/**
 * Central source of truth for a store's local primary-key column.
 *
 * Both the sync engine and the hub till-client must resolve upsert keys through
 * here so the two paths can never drift (a mismatch silently corrupts upserts).
 */
export function getPrimaryKeyForTable(idbStore: string): string {
	return PRIMARY_KEY_BY_STORE[idbStore] || "name";
}

export const SYNC_DEFAULTS = {
	intervalMs: 5 * 60 * 1000,
	pushIntervalMs: 30 * 1000,
	maxRetries: 3,
	onlineGracePeriodMs: 3_000,
	businessHoursStart: 9,
	businessHoursEnd: 21,
};
